import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
  },
  image: {
    flex: 1,
    backgroundColor: 'rgba(52, 52, 52, 0.2)',
    height: 200,
    zIndex: 0,
    // marginTop: 20,
  },
  vehicleFinder: {
    backgroundColor: '#393939',
    marginTop: '-5%',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    height: 220,
  },
  adminFinder: {
    backgroundColor: '#FFF',
    marginTop: '-5%',
    height: 150,
    marginBottom: 10,
  },
  finderRow: {
    marginHorizontal: 5,
    marginBottom: 20,
    height: 50,
    flexDirection: 'row',
    justifyContent: 'space-evenly',
  },
  textInput: {
    marginTop: 20,
    borderRadius: 10,
    height: '100%',
    backgroundColor: 'rgba(250, 250, 250, 0.4)',
    width: '50%',
    fontFamily: 'Nunito-Regular',
    borderColor: 'black',
    borderWidth: 1,
  },
  pickerView: {
    borderRadius: 10,
    marginTop: 20,
    backgroundColor: 'rgba(250, 250, 250, 0.4)',
    height: '100%',
    width: '45%',
    fontFamily: 'Nunito-Regular',
    borderColor: 'black',
    borderWidth: 1,
  },
  buttonArea: {
    marginBottom: 70,
  },
  findButton: {
    backgroundColor: '#FFCD61',
    marginHorizontal: 20,
    marginTop: 20,
    marginBottom: 40,
    justifyContent: 'center',
    alignItems: 'center',
    height: '40%',
    borderRadius: 10,
  },
  buttonText: {
    fontFamily: 'Nunito-Black',
    fontSize: 18,
  },
  recommended: {
    backgroundColor: '#FFF',
    marginVertical: 10,
  },
  recommendedHeading: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    margin: 10,
  },
  cardImage: {
    width: 250,
    height: 150,
    margin: 10,
    borderRadius: 10,
  },
  recommendedTitle: {
    fontFamily: 'Nunito-Black',
    fontSize: 18,
  },
  viewMore: {
    fontFamily: 'Nunito-Black',
    fontSize: 12,
  },
  date: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  datePicker: {
    marginTop: 20,
    width: '45%',
    height: '100%',
    fontSize: 16,
    borderRadius: 10,
    backgroundColor: 'rgba(240, 240, 240, 0.4)',
    marginVertical: 10,
    justifyContent: 'center',
    paddingLeft: 20,
    borderColor: 'black',
    borderWidth: 1,
  },
  dateText: {
    fontSize: 18,
  },
  addView: {
    height: 100,
    marginBottom: -20,
  },
  addNewItem: {
    margin: 10,
    backgroundColor: '#393939',
    height: '50%',
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  addText: {
    color: '#FFCD61',
    fontFamily: 'Nunito-Black',
    fontSize: 18,
  },
});
